name: generate_reflection
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.4.0
  universal_html:
    path: '..'

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^6.0.0